apiVersion: v1
kind: Service
metadata:
  labels:
    app: webhook-ansible
  name: webhook-ansible
spec:
  ports:
  - name: 9000-tcp
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    deploymentconfig: webhook-ansible
  sessionAffinity: None
  type: ClusterIP
