apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-ansible-sso-creds
  labels:
    app: webhook-ansible
data:
  sso_vars.yml: |-
    ---
    # vars file for keycloakrealm
    environments: 
      - dev
      - test
      - prod
    # ----dev----
    dev_keycloak_client_id: 
    dev_keycloak_url: 
    dev_keycloak_client_secret: 
    # ----test----
    test_keycloak_client_id: 
    test_keycloak_url: 
    test_keycloak_client_secret: 
    # ----prod----
    prod_keycloak_client_id: 
    prod_keycloak_url: 
    prod_keycloak_client_secret: 
    # ----admin----
    admin_idp: 
    token_data: placeholder
    ldap_host: 
    ldap_username: 
    ldap_password: 
