---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    creds/sso_vars.yml
  vars:
  # load realms settings
  - app_realm_data: "{{ lookup('file', 'inputs/realm-content-app.json') | from_json }}"
  - idir_realm_data: "{{ lookup('file', 'inputs/realm-content-idir.json') | from_json }}"
  - github_realm_data: "{{ lookup('file', 'inputs/realm-content-github.json') | from_json }}"
  # path to different tasks:
  - reuse_tasks: ../../tasks
  tasks:

  # Notes: with custom setup, the realm will be created with the extra settings:
  # (see templates)
  # 1. allow duplicate email
  # 2. using BCGov login theme
  - name: check for custom settings
    set_fact:
      custom: action == "ocp4-setup"

  - name: Setup SSO instance with IDP and app realms
    include_tasks: tasks/sso-prep.yml
    with_items: 
      - "{{ environments }}"
    loop_control: 
      loop_var: env
    when: action == "config-keycloak"

  # For OCP4 login or K6 testing setup, update the app_realm_data content and specify what are the IDPs needed
  - name: Provision new SSO realms
    include_tasks: tasks/sso-provisioning.yml
    vars:
    - realm_data: "{{ app_realm_data }}"
    with_items: 
      - "{{ environments }}"
    loop_control: 
      loop_var: env
    when: action == "new-realm" or action == "ocp4-setup" or action == "k6-setup"

  - name: Config ocp4 realm
    include_tasks: tasks/ocp4-setup.yml
    vars:
    - realm_data: "{{ app_realm_data }}"
    with_items: 
      - "{{ environments }}"
    loop_control: 
      loop_var: env
    when: action == "ocp4-setup"

  - name: Config k6 realm
    include_tasks: tasks/k6-setup.yml
    vars:
    - realm_data: "{{ app_realm_data }}"
    with_items: 
      - "{{ environments }}"
    loop_control: 
      loop_var: env
    when: action == "k6-setup"
