---
- hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    creds/sso_vars.yml
  vars:
  # load realms settings
  - app_realm_data: "{{ lookup('file', 'inputs/realm-content-app.json') | from_json }}"
  - idir_realm_data: "{{ lookup('file', 'inputs/realm-content-idir.json') | from_json }}"
  - github_realm_data: "{{ lookup('file', 'inputs/realm-content-github.json') | from_json }}"
  - bceid_both_realm_data: "{{ lookup('file', 'inputs/realm-content-bceid-both.json') | from_json }}"
  - bceid_business_realm_data: "{{ lookup('file', 'inputs/realm-content-bceid-business.json') | from_json }}"
  - bceid_basic_realm_data: "{{ lookup('file', 'inputs/realm-content-bceid-basic.json') | from_json }}"

  # path to different tasks:
  - reuse_tasks: ../../tasks
  tasks:

  # Notes: with custom setup, the realm will be created with the extra settings:
  # (see templates)
  # 1. allow duplicate email
  # 2. using BCGov login theme
  - name: check for custom settings
    set_fact:
      custom: action == "ocp4-setup"

  - name: Setup SSO instance with IDP and app realms
    include_tasks: tasks/sso-prep.yml
    with_items: 
      - "{{ environments }}"
    loop_control: 
      loop_var: env
    when: action == "config-keycloak"

  - name: Setup SSO instance with bceid realms
    include_tasks: tasks/sso-prep-bceid.yml
    with_items: 
      - "{{ environments }}"
    loop_control: 
      loop_var: env
    when: action == "config-keycloak-bceid"

  # For OCP4 login or K6 testing setup, update the app_realm_data content and specify what are the IDPs needed
  - name: Provision new SSO realms
    include_tasks: tasks/sso-provisioning.yml
    vars:
    - realm_data: "{{ app_realm_data }}"
    with_items: 
      - "{{ environments }}"
    loop_control: 
      loop_var: env
    when: action == "new-realm" or action == "ocp4-setup"

  - name: Config ocp4 realm
    include_tasks: tasks/ocp4-setup.yml
    vars:
    - realm_data: "{{ app_realm_data }}"
    with_items: 
      - "{{ environments }}"
    loop_control: 
      loop_var: env
    when: action == "ocp4-setup"

  - name: Add new IDPs or enable BCeID
    include_tasks: tasks/manage-idp.yml
    vars:
    - realm_data: "{{ app_realm_data }}"
    with_items: 
      - "{{ environments }}"
    loop_control: 
      loop_var: env
    when: action == "new-idp" or action == "enable-prod-bceid"

  - pause:
      prompt: "Are you sure to delete realm {{ app_realm_data.realm.id }} ? (yes/no)"
    register: delete_confirmed
    when: action == "delete-realm"

  - name: Delete realm
    include_tasks: tasks/delete-realm.yml
    vars:
    - realm_data: "{{ app_realm_data }}"
    with_items: 
      - "{{ environments }}"
    loop_control: 
      loop_var: env
    when: action == "delete-realm" and delete_confirmed.user_input == "yes"  

  - name: Create "{{ count }}" K6 realms in total
    include_tasks: tasks/k6-main.yml
    vars:
    - realm_data: "{{ app_realm_data }}"
    with_sequence: start=0 end="{{ count | int - 1 }}"
    when: action == "k6-setup"
