---
# vars file for keycloakrealm
environments: 
  - dev
  - test
  - prod
# ----dev----
dev_keycloak_client_id:
dev_keycloak_url: 
dev_keycloak_client_secret:
# ----test----
test_keycloak_client_id:
test_keycloak_url: 
test_keycloak_client_secret:
# ----prod----
prod_keycloak_client_id:
prod_keycloak_url: 
prod_keycloak_client_secret:
# ----sandbox----
sbox_keycloak_client_id:
sbox_keycloak_url: 
sbox_keycloak_client_secret:

admin_idp: idir
token_data: placeholder
ldap_host: ldap://idir.bcgov
ldap_username: IDIR\xxx
ldap_password: 
