---
#tasks file for deleting new realm

## Clean Realm
- name: Check if realm exists
  uri: 
    url: "{{ keycloak_url }}/auth/admin/realms/{{ realm_name }}"
    method: GET
    body_format: json
    return_content: yes
    headers: 
      Authorization: "Bearer {{ token_data }}"
  register: realm_status
  ignore_errors: true
- name: Set realm id fact
  set_fact:
    realm_id: "{{ realm_status.json.id | default('') }}"

- debug: msg="--------NO REALM FOUND - {{ realm_name }} - {{ env }}"
  when: realm_id == ""


- debug: msg="--------DELETE REALM {{ realm_id }} in the {{ env }}"
  when: realm_id != ""

- name: Delete realm
  uri: 
    url: "{{ keycloak_url }}/auth/admin/realms/{{ realm_id }}"
    method: DELETE
    headers: 
      Authorization: "Bearer {{ token_data }}"
    return_content: yes
    status_code: 204
  when: realm_id != ""
