---
# tasks to create realm with provided configs
# - create realm
# - setup app realm with IDP pointing to IDP realms
# - create admin user

- name: Setup keycloak variables for the environment
  set_fact: 
    keycloak_url: "{{ lookup('vars', env + '_keycloak_url') }}"
    grant_type: "{{ lookup('vars', env + '_grant_type') }}"
    keycloak_user_id: "{{ lookup('vars', env + '_keycloak_user_id') }}"
    keycloak_user_password: "{{ lookup('vars', env + '_keycloak_user_password') }}"
    otp_code: "{{ lookup('vars', env + '_otp_code') }}"
    keycloak_client_id: "{{ lookup('vars', env + '_keycloak_client_id') }}"
    keycloak_client_secret: "{{ lookup('vars', env + '_keycloak_client_secret') }}"

- name: Get access token
  include_tasks: access-token.yml

- name: Create new realm
  include_tasks: "{{ reuse_tasks }}/realm_tasks/create-realm.yml"

- name: Update access token
  include_tasks: access-token.yml

# --------------------TODO: Update Realm Reviewer
# --------------------TODO: Disabling `Review Profile` on `First Broker Login`
# --------------------TODO: add client request type in IDP creation`

# Link to IDP Realms, separately for each ID
# NOTE: BCeID will not be enabled in Production
- name: Link to IDP Realms
  include_tasks: "{{ reuse_tasks }}/realm_tasks/link-idp-realm.yml"
  vars:
  - realm: "{{ realm_data.realm.id }}"
  with_items: "{{ realm_data.realm.idps }}"
  loop_control:
    loop_var: idp_name
  # when: env != "prod" or idp_name != "BCeID"

- name: Update access token
  include_tasks: access-token.yml

# Add admin user
- name: Add admin user
  include_tasks:  "{{ reuse_tasks }}/realm_tasks/admin-user.yml"
  vars:
  - realm: "{{ realm_data.realm.id }}"
  - admin_username: "{{ realm_data.realm.adminUser }}"
  when: action != "k6-setup"
