---
# Use this task list to config keycloak instances
# - create IDP realms: IDIR/GitHub
# - setup IDP realms with IDP and mappers
# - create app realm
# - setup app realm with IDP pointing to IDP realms

- name: Setup keycloak variables for the environment
  set_fact: 
    keycloak_url: "{{ lookup('vars', env + '_keycloak_url') }}"
    grant_type: "{{ lookup('vars', env + '_grant_type') }}"
    keycloak_user_id: "{{ lookup('vars', env + '_keycloak_user_id') }}"
    keycloak_user_password: "{{ lookup('vars', env + '_keycloak_user_password') }}"
    otp_code: "{{ lookup('vars', env + '_otp_code') }}"
    keycloak_client_id: "{{ lookup('vars', env + '_keycloak_client_id') }}"
    keycloak_client_secret: "{{ lookup('vars', env + '_keycloak_client_secret') }}"

- name: Get access token
  include_tasks: access-token.yml

# Setup IDIR
- name: Create IDIR Realms
  include: "{{ reuse_tasks }}/realm_tasks/create-realm.yml"
  vars:
  - realm_data: "{{ idir_realm_data }}"

- name: Update access token
  include_tasks: access-token.yml

- name: Setup IDP in IDIR realm
  include_tasks: create-idp.yml
  vars:
  - idp_realm_id: "{{ idir_realm_data.realm.id }}"
  - idp_realm_alias: "{{ idir_realm_data.realm.idp }}"

# Setup GitHub
- name: Create GitHub Realms
  include_tasks: "{{ reuse_tasks }}/realm_tasks/create-realm.yml"
  vars:
  - realm_data: "{{ github_realm_data }}"

- name: Update access token
  include_tasks: access-token.yml

- name: Setup IDP in GitHub realm
  include_tasks: create-idp.yml
  vars:
  - idp_realm_id: "{{ github_realm_data.realm.id }}"
  - idp_realm_alias: "{{ github_realm_data.realm.idp }}"

# Setup App realm
- name: Create Realms
  include_tasks: "{{ reuse_tasks }}/realm_tasks/create-realm.yml"
  vars:
  - realm_data: "{{ app_realm_data }}"

- name: Update access token
  include_tasks: access-token.yml

- name: Link to IDP Realms
  include_tasks: "{{ reuse_tasks }}/realm_tasks/link-idp-realm.yml"
  vars:
  - realm: "{{ app_realm_data.realm.id }}"
  with_items: "{{ app_realm_data.realm.idps }}"
  loop_control:
    loop_var: idp_name
